### ISSUE TITLE
blacklist in argparse breaks xicam

### ISSUE THREAD

**Issue by ercius** [synchrotrons/Xi-cam.core#24]
Just pulled xicam. Error produced by new 'blacklist' keyword in argparse when starting xicam. XIcam will not run.

Error:
```
Traceback (most recent call last):
  File "C:\Users\linol\AppData\Local\Continuum\anaconda3\envs\xicam2\Scripts\xicam-script.pyw", line 11, in <module>
    load_entry_point('xicam', 'gui_scripts', 'xicam')()
  File "c:\users\linol\documents\scripting\xi-cam\run_xicam.py", line 51, in main
    args = parse_args(exit_on_fail=True)
  File "c:\users\linol\documents\scripting\xi-cam.core\xicam\core\args\__init__.py", line 36, in parse_args
    help="prevent Xi-cam from loading a plugin by name", nargs="+", type=str)
  File "C:\Users\linol\AppData\Local\Continuum\anaconda3\envs\xicam2\lib\argparse.py", line 1352, in add_argument
    raise ValueError('unknown action "%s"' % (action_class,))
ValueError: unknown action "extend"
````

If you comment out this new keyword then everything runs as expected.

**Comment by ronpandolfi** [comment]
Resolved by switching to `"append"` in 610a7c63ec59b697802343464a2834247575aa2f
