### ISSUE TITLE
msg crashes xicam on startup

### ISSUE THREAD

**Issue by ercius** [synchrotrons/Xi-cam.core#8]
Using windows 10 and anaconda with python 3.7.4

I just pulled everything from the repos and receive this message when starting xicam:

```ERROR:main:Wed Oct 23 10:25:57 2019 - main - ERROR - M - 
 Traceback (most recent call last):
   File "c:\users\linol\documents\scripting\xi-cam.gui\xicam\gui\windows\splash.py", line 90, in restartmovie
    self.execlaunch()
   File "c:\users\linol\documents\scripting\xi-cam.gui\xicam\gui\windows\splash.py", line 109, in execlaunch
    from xicam.gui.windows.mainwindow import XicamMainWindow
   File "c:\users\linol\documents\scripting\xi-cam.gui\xicam\gui\windows\mainwindow.py", line 7, in <module>
    from xicam.plugins.guiplugin import PanelState
   File "c:\users\linol\documents\scripting\xi-cam.plugins\xicam\plugins\__init__.py", line 14, in <module>
    from xicam.core import msg
   File "c:\users\linol\documents\scripting\xi-cam.core\xicam\core\msg\__init__.py", line 282, in <module>
    faulthandler.enable()
 RuntimeError: sys.stderr is None
```
If I comment out this line then I get past this issue:
https://github.com/synchrotrons/Xi-cam.core/blob/75606554d523c59f4c01dbb3a83df4df677b11bf/xicam/core/msg/__init__.py#L282

**Comment by ronpandolfi** [comment]
This should be resolved with 34c99928850bb7610c85ad9b6341b9d1627f16b4 . This was a result of pythonw.exe on windows not having a `sys.stderr` to attach to. Now, the crash log will be written into `user_cache_dir` in this case.
